version: "3.8"
services:
  app:
    build: .
    container_name: invoice_management_container
    image: invoice_management:1.0
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: invoice_management
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - invoice_management_volume:/var/lib/mysql
volumes:
  invoice_management_volume:
